include make.common

plumbing_test: plumbing_test.cpp
	g++ plumbing_test.cpp -o plumbing_test $(ALL_FLAGS)

smoke_test: smoke_test$(PYTHON_EXTENSION_SUFFIX) ;

hello_world: hello_world$(PYTHON_EXTENSION_SUFFIX) ;
